name: DateApp
description: "A Tinder-like dating app built with Flutter. Features include swipeable profile cards, matching animations, and a modern UI design. The app demonstrates smooth card animations, gesture controls, and responsive design principles."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
